#!/usr/bin/env ruby


require_relative 'lib/month'
#require_relative 'lib/year'

month = ARGV[0].to_i
year = ARGV[1].to_i

if ARGV.length > 2
  puts "cal: year #{year} not in range 1800...3000"
  exit
end

begin
  if ARGV.length < 2
    year = Year.new(ARGV[0])
  else
    month = Month.new(month,year)
    puts month.to_s
  end
rescue ArgumentError => e
  puts e.message
end
